# Generated by Django 5.2.5 on 2025-08-18 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_email_verified_user_is_email_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='subjects',
            field=models.CharField(default='General', help_text='Subject(s) or specialization', max_length=255),
        ),
    ]
