# Generated by Django 5.2.5 on 2025-08-18 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_subjects_to_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='password_change_required',
            field=models.BooleanField(default=True, help_text='Teacher must change password on first login'),
        ),
    ]
