# Generated by Django 5.2.5 on 2025-08-21 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_password_change_required_to_teacher'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
