# Generated by Django 5.2.5 on 2025-08-26 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_user_password_reset_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningactivity',
            name='learning_objectives',
            field=models.TextField(blank=True, help_text='Learning goals and objectives for this activity'),
        ),
        migrations.AddField(
            model_name='learningactivity',
            name='materials_used',
            field=models.TextField(blank=True, help_text='Materials and resources used in this activity'),
        ),
    ]
