# Generated by Django 5.2.5 on 2025-09-05 16:57

import core.simple_story_models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_story_storyattachment_storycomment_storylike'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('story_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video'), ('file', 'File'), ('journal', 'Journal')], default='journal', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simple_stories', to='core.teacher')),
            ],
            options={
                'db_table': 'simple_stories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SimpleStoryAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=core.simple_story_models.story_file_path)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveBigIntegerField()),
                ('file_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.simplestory')),
            ],
            options={
                'db_table': 'simple_story_attachments',
            },
        ),
        migrations.CreateModel(
            name='SimpleStoryComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.simplestory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'simple_story_comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SimpleStoryLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='core.simplestory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'simple_story_likes',
                'unique_together': {('story', 'user')},
            },
        ),
    ]
